### ISSUE TITLE
Cream Cheese necessary?

### ISSUE THREAD

**Issue by jacobmunson** [EriqLaplus/chickendipR#3]
Let's say I went Pandemic-era shopping and forget cream cheese, and I don't want to go shopping again for a long while, but I do want chicken dip. Advice on how to proceed?

**Comment by jordans1882** [comment]
A great question! Currently the chickendipR API doesn't support substitutes. Perhaps @EriqLaplus can open a feature request project board where such a thing could be resolved? I could be way off base here, but I think the chickendipR class structure will need to be extended to include ingredient class objects which in turn contain a substitutes field...

**Comment by EriqLaplus** [comment]
Hi Jacob,

The community has reached out to you and offered a solution. Please let us
know if our proposed solution works for you. Thank you for bringing this
concern to our attention.

- chickendipR Team

**Comment by jacobmunson** [comment]
@EriqLaplus unexpectedly and kindly delivered cream cheese to my doorstep, and maintained social distancing at that! While I have not doubted the generosity and kindness of the open source community, this is yet another shining example of the quality work and commitment of this open source chicken dip community. Truly a blessing.
